export const FETCH_WEATHER = "COMMAND/FETCH_WEATHER_FOR_LAT_LNG";
export const WEATHER_ID_RECEIVED = "EVENT/WEATHER_ID_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const FETCH_LOCATION = "COMMAND/FETCH_LOCATION";
export const GET_DRONE_LOCATION = "EVENT/GET_DRONE_LOCATION";
export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
